language: cpp 

sudo: required

services:
 - docker

env:
  matrix:
    - DISTRO=fedora DOCKERHUB=true
    - DISTRO=fedora_gmx5.1 GMX_BRANCH=release-5-1 DOCKERHUB=true
    - DISTRO=fedora_gmx2016 GMX_BRANCH=release-2016 DOCKERHUB=true
    - DISTRO=fedora_gmx9999 GMX_BRANCH=master DOCKERHUB=true
    - DISTRO=ubuntu DOCKERHUB=true

script:
  - mkdir ${HOME}/docker
  - cp -v ${DISTRO%_*} ${HOME}/docker/Dockerfile
  - cp -r $HOME/.ccache ${HOME}/docker/ccache
  - if [[ ${DISTRO} = fedora ]]; then DISTRO="latest"; fi
  - if [[ ${TRAVIS_BRANCH} != master ]]; then TAG="${TAG}_${TRAVIS_BRANCH}"; fi
  - docker build --build-arg GMX_BRANCH="${GMX_BRANCH}"
                 -t ${TRAVIS_REPO_SLUG}:${DISTRO}${TAG} ${HOME}/docker/ &&
    rm -rf $HOME/.ccache &&
    CON=$(docker run -d ${TRAVIS_REPO_SLUG}:${DISTRO}${TAG} /bin/bash) &&
    docker cp ${CON}:/home/votca/.ccache ${HOME}/

after_success:
  - shopt -s extglob && [[ ${TRAVIS_BRANCH} = @(master|refactor) ]] && DEPLOY=yes
  - if [[ ${DOCKERHUB} = true && ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${TRAVIS_PULL_REQUEST} == false && ${DEPLOY} ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push "${TRAVIS_REPO_SLUG}:${DISTRO}${TAG}";
   fi

cache:
  - ccache

compiler:
  - gcc

notifications:
  email:
    - votca-commits@googlegroups.com
