name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 1 * * FRI'

jobs:
  CI:
    continue-on-error: ${{ matrix.config.tag == 'ubuntu_devel' || matrix.config.tag == 'fedora_rawhide' }}
    strategy:
      matrix:
        config:
          - {tag: 'latest', dockerfile: 'fedora'}
          - {tag: 'fedora_rawhide', dockerfile: 'fedora', build_args: 'PYTHON=python3.9,TAG=rawhide'}
          - {tag: 'ubuntu', dockerfile: 'ubuntu'}
          - {tag: 'ubuntu_rolling', dockerfile: 'ubuntu', build_args: 'TAG=rolling'}
          - {tag: 'ubuntu_devel', dockerfile: 'ubuntu', build_args: 'TAG=devel'}
          - {tag: 'ubuntu_18.04', dockerfile: 'ubuntu', build_args: 'TAG=18.04'}
          - {tag: 'opensuse', dockerfile: 'opensuse'}
          - {tag: 'fedora_gmx2019_d', dockerfile: 'fedora', build_args: 'GMX_BRANCH=release-2019,GMX_DOUBLE=ON'}
          - {tag: 'fedora_gmx2019', dockerfile: 'fedora', build_args: 'GMX_BRANCH=release-2019'}
          - {tag: 'fedora_gmx2020_d', dockerfile: 'fedora', build_args: 'GMX_BRANCH=release-2020,GMX_DOUBLE=ON'}
          - {tag: 'fedora_gmx2020', dockerfile: 'fedora', build_args: 'GMX_BRANCH=release-2020'}
          - {tag: 'fedora_gmx9999_d', dockerfile: 'fedora', build_args: 'GMX_BRANCH=master,GMX_DOUBLE=ON'}
          - {tag: 'fedora_gmx9999', dockerfile: 'fedora', build_args: 'GMX_BRANCH=master'}
          - {tag: 'fedora_nogmx', dockerfile: 'fedora', build_args: 'GMX_BRANCH=none'}
          - {tag: 'intel', dockerfile: 'fedora', build_args: 'INTEL=yes'}
          - {tag: 'actions', dockerfile: 'actions'}
          - {tag: 'format', dockerfile: 'format'}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Docker images for Docker Hub
        uses: docker/build-push-action@v1.1.0
        with:
          repository: votca/buildenv
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ matrix.config.tag }}
          dockerfile: ${{ matrix.config.dockerfile }}
          build_args: ${{ matrix.config.build_args }}
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
      - name: Build Docker images for Github
        uses: docker/build-push-action@v1.1.0
        with:
          repository: votca/buildenv/${{ matrix.config.tag }}
          registry: docker.pkg.github.com
          username: votca-bot
          password: ${{ secrets.VOTCA_BOT_TOKEN }}
          tags: latest
          dockerfile: ${{ matrix.config.dockerfile }}
          build_args: ${{ matrix.config.build_args }}
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
      - name: Build Docker images for GitLab
        uses: docker/build-push-action@v1.1.0
        with:
          repository: votca/buildenv/${{ matrix.config.tag }}
          registry: registry.gitlab.com
          username: votca-bot
          password: ${{ secrets.GITLAB_BUILDENV_TOKEN }}
          tags: latest
          dockerfile: ${{ matrix.config.dockerfile }}
          build_args: ${{ matrix.config.build_args }}
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
