name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 1 * * FRI'

jobs:
  CI:
    continue-on-error: ${{ matrix.continue-on-error == true }}
    strategy:
      matrix:
        config:
          - {tag: 'latest',    dockerfile: 'fedora'}
          - {tag: 'rawhide',   dockerfile: 'fedora', build_args: 'PYTHON=python3.9,TAG=rawhide', continue-on-error: 'true'}
          - {tag: 'latest',    dockerfile: 'ubuntu'}
          - {tag: 'rolling',   dockerfile: 'ubuntu', build_args: 'TAG=rolling'}
          - {tag: 'devel',     dockerfile: 'ubuntu', build_args: 'TAG=devel', continue-on-error: 'true'}
          - {tag: '18.04',     dockerfile: 'ubuntu', build_args: 'TAG=18.04'}
          - {tag: 'latest',    dockerfile: 'opensuse'}
          - {tag: 'latest',    dockerfile: 'gentoo'}
          - {tag: 'gmx2019_d', dockerfile: 'fedora', build_args: 'GMX_BRANCH=release-2019,GMX_DOUBLE=ON'}
          - {tag: 'gmx2019',   dockerfile: 'fedora', build_args: 'GMX_BRANCH=release-2019'}
          - {tag: 'gmx2020_d', dockerfile: 'fedora', build_args: 'GMX_BRANCH=release-2020,GMX_DOUBLE=ON'}
          - {tag: 'gmx2020',   dockerfile: 'fedora', build_args: 'GMX_BRANCH=release-2020'}
          - {tag: 'gmx9999_d', dockerfile: 'fedora', build_args: 'GMX_BRANCH=master,GMX_DOUBLE=ON'}
          - {tag: 'gmx9999',   dockerfile: 'fedora', build_args: 'GMX_BRANCH=master'}
          - {tag: 'nogmx',     dockerfile: 'fedora', build_args: 'GMX_BRANCH=none'}
          - {tag: 'intel',     dockerfile: 'fedora', build_args: 'INTEL=yes'}
          - {tag: 'latest',    dockerfile: 'actions'}
          - {tag: 'latest',    dockerfile: 'format'}
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker images for GitLab
        uses: docker/build-push-action@v1.1.0
        with:
          repository: votca/buildenv/${{ matrix.config.dockerfile }}
          registry: registry.gitlab.com
          username: votca-bot
          password: ${{ secrets.GITLAB_REGISTRY_TOKEN }}
          tags: ${{ matrix.config.tag }}
          dockerfile: ${{ matrix.config.dockerfile }}
          build_args: ${{ matrix.config.build_args }}
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
      - name: Build Docker images for Github Container Registry
        uses: docker/build-push-action@v1.1.0
        with:
          repository: votca/buildenv/${{ matrix.config.dockerfile }}
          registry: ghcr.io
          username: votca-bot
          password: ${{ secrets.VOTCA_BOT_TOKEN }}
          tags: ${{ matrix.config.tag }}
          dockerfile: ${{ matrix.config.dockerfile }}
          build_args: ${{ matrix.config.build_args }}
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
