name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 1 * * FRI'

jobs:
  CI:
    continue-on-error: ${{ matrix.config.continue-on-error == 'true' }}
    strategy:
      matrix:
        config:
          - {dockerfile: 'fedora',   tag: 'latest'}
          - {dockerfile: 'fedora',   tag: 'rawhide',      build_args: 'TAG=rawhide,PYTHON=python3.10', continue-on-error: 'true'}
          - {dockerfile: 'ubuntu',   tag: 'latest'}
          - {dockerfile: 'ubuntu',   tag: 'rolling',      build_args: 'TAG=rolling'}
          - {dockerfile: 'ubuntu',   tag: 'devel',        build_args: 'TAG=devel', continue-on-error: 'true'}
          - {dockerfile: 'opensuse', tag: 'latest', continue-on-error: 'true'}
          - {dockerfile: 'fedora',   tag: 'gmx2019_d',    build_args: 'GMX_BRANCH=release-2019,GMX_DOUBLE=ON'}
          - {dockerfile: 'fedora',   tag: 'gmx2019',      build_args: 'GMX_BRANCH=release-2019'}
          - {dockerfile: 'fedora',   tag: 'gmx2021_d',    build_args: 'GMX_BRANCH=release-2021,GMX_DOUBLE=ON'}
          - {dockerfile: 'fedora',   tag: 'gmx2021',      build_args: 'GMX_BRANCH=release-2021'}
          - {dockerfile: 'fedora',   tag: 'gmx9999_d',    build_args: 'GMX_BRANCH=master,GMX_DOUBLE=ON', continue-on-error: 'true'}
          - {dockerfile: 'fedora',   tag: 'gmx9999',      build_args: 'GMX_BRANCH=master', continue-on-error: 'true'}
          - {dockerfile: 'fedora',   tag: 'nogmx',        build_args: 'GMX_BRANCH=none'}
          - {dockerfile: 'fedora',   tag: 'intel',        build_args: 'TAG=33,INTEL=yes'}
          - {dockerfile: 'actions',  tag: 'latest'}
          - {dockerfile: 'format',   tag: 'latest'}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v2
      - name: Build Docker images for GitLab
        uses: docker/build-push-action@v1
        with:
          repository: votca/buildenv/${{ matrix.config.dockerfile }}
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
          password: ${{ secrets.GITLAB_REGISTRY_TOKEN }}
          tags: ${{ matrix.config.tag }}
          dockerfile: ${{ matrix.config.dockerfile }}
          build_args: ${{ matrix.config.build_args }}
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
      - name: Build Docker images for Github Container Registry
        uses: docker/build-push-action@v1
        with:
          repository: votca/buildenv/${{ matrix.config.dockerfile }}
          registry: ghcr.io
          # username do not matter, but needs to be a secret, so it gets nulled out on PR from forks
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.VOTCA_BOT_TOKEN }}
          tags: ${{ matrix.config.tag }}
          dockerfile: ${{ matrix.config.dockerfile }}
          build_args: ${{ matrix.config.build_args }}
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
